stages:
  - build
  - publish

variables:
  GIT_SUBMODULE_STRATEGY: recursive


build:psp-gcc:
  stage: build
  image: haydenkow/nu-pspdev:latest
  script:
    - make release
  artifacts:
    paths:
    - libintraFont.tar.gz

publish:
  stage: publish
  image: inetprocess/gitlab-release
  only:
    - tags
  script:
    - gitlab-release --message 'ADD TEMPLATE HERE' libintraFont.tar.gz

