CC = gcc

TARGET = fonttest
OBJS = fonttest.o

INCDIR = ../../include
CFLAGS = -Wall -Wextra -I$(INCDIR)

LIBDIR = ../../lib
LDFLAGS = -L$(LIBDIR)
LIBS = -lintrafont_lin -lglfw -lGL -lm

all: $(TARGET)

debug: CFLAGS += -O0 -g
debug: $(TARGET)

release: CFLAGS += -Os -s
release: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $^ $(LIBS)

clean:
	-rm -f $(OBJS) $(TARGET)